name: PipeLine

on: 
  push: 
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Check HTML and CSS with HTML5 validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./
          css: true

  delivery: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout repository code into runner
        uses: actions/checkout@v2
      - name: build the docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/website-test:latest .
      - name: log into docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: push the image to docker hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/website-test:latest 
